server:
  port: 10000
spring:
  application:
    # 多个注册中心，名称一定要写成一样的，否则会出现available-replicas
    name: eureka-registy-center
eureka:
  instance:
    # 写localhost会导致web页面看不到registered-replicas
    hostname: eureka1.com
  client:
    # 这两个参数集群模式配置为true，默认值。单机模式配置为false。
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #写localhost会出现available-replicas
      defaultZone: http://eureka2.com:10001/eureka