server:
  port: 9000
spring:
  application:
    name: sso
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  config: classpath:logback-spring.xml