server:
  port: 9002
spring:
  application:
    name: sso-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 10
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000
        min-idle: 2
        max-idle: 5
    timeout: 10000
logging:
  config: classpath:logback-spring.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka,http://localhost:10001/eureka